### ISSUE TITLE
0.1 Roadmap

### ISSUE THREAD

**Issue by thautwarm** [thautwarm/Traffy.UnityPython#7]
A short intro to the architecture (you can escape this and see the roadmap)
------

We have five parts to implement:
- **language features**. For instance, `import` statement is a lang feature. Such part includes PythonAST-to-TraffyASM compilation, and its interpretation in .NET side.
 related source code:
  - [Traffy ASM interpreter](https://github.com/thautwarm/TraffyAsm.UnityPython/tree/main/UnityPython.BackEnd/src/Traffy.Asm)
  - [UnityPython.FrontEnd](https://github.com/thautwarm/TraffyAsm.UnityPython/tree/main/UnityPython.FrontEnd)
- **built-in functions and types**: built-in functions like `print`, `map`, and builtin types like `list` and `Exception`
    related source code
    - [UnityPython.BackEnd/src/Traffy.Runtime/Builtins.cs](https://github.com/thautwarm/TraffyAsm.UnityPython/blob/main/UnityPython.BackEnd/src/Traffy.Runtime/Builtins.cs)
    - [UnityPython.BackEnd/src/Traffy.Asm/*.cs](https://github.com/thautwarm/TraffyAsm.UnityPython/tree/main/UnityPython.BackEnd/src/Traffy.Objects)

- **runtime mechanisms**, such as inline cache (for fast attribute reading and writing), coroutine implementations, traceback system, fast method call, etc.
   backend code is more or less related to this topic, but for specific sub-topics:
   - inline cache:
     - [UnityPython.BackEnd/src/ICInfrastructure/*.cs](https://github.com/thautwarm/TraffyAsm.UnityPython/tree/main/UnityPython.BackEnd/src/ICInfrastructure)
     - [UnityPython.BackEnd/src/Traffy.Objects/Object.IC.cs](https://github.com/thautwarm/TraffyAsm.UnityPython/tree/main/UnityPython.BackEnd/Traffy.Objects/Class.IC.cs)
     - [UnityPython.BackEnd/src/Traffy.Objects/Object.IC.cs](https://github.com/thautwarm/TraffyAsm.UnityPython/tree/main/UnityPython.BackEnd/Traffy.Objects/Class.IC.cs)
   - [coroutine (via .NET Task-like types)](https://github.com/thautwarm/TraffyAsm.UnityPython/blob/main/UnityPython.BackEnd/src/Datatypes/MonoAsync.cs)

  The implementation of Python data model (objects, classes, `__init__`, `__new__`, a lot) is roughly a duplicate of CPython, what I've done is just figuring out a maintainable and efficient approach.
- **tooling**, mainly about IDE support. [`UnityPython.BackEnd/traffy-types/builtins.pyi`](https://github.com/thautwarm/TraffyAsm.UnityPython/blob/main/UnityPython.BackEnd/traffy-types/builtins.pyi) can instruct Pylance to analyze UnityPython source. **When a new builtin is implemented, we should add type hints in [`traffy-types/builtins.pyi`](https://github.com/thautwarm/TraffyAsm.UnityPython/blob/main/UnityPython.BackEnd/traffy-types/builtins.pyi) to support the new stuffs.**
- **Unity/game engine**: we will finally generate Unity API bindings for UnityPython.

Roadmap
---

- language features
  Most of the language features have been already supported, see `UnityPython.FrontEnd`.
  The complete Python ASTs are defined at [Python 3.10 ASDL](https://raw.githubusercontent.com/python/cpython/3.10/Parser/Python.asdl)

  [What have been supported](https://github.com/thautwarm/TraffyAsm.UnityPython/blob/master/UnityPython.FrontEnd/unitypython/Scoper.py#L58).

  - [x] `with`
  - [x] `await`, `async`, `await Task.Yield`
  - [x] `FormattedValue`, `JoinedStr` (**NOTE**: ascii conversions (`{x:a}`) and format specifiers (`{a:.2}`) are not supported)
  - [x] delete variables/~attributes~/subscripts: `del a; del a[b]; del a.b`
  - [x] comprehension expressions: `ListComp`, `SetComp`, `DictComp`, `GeneratorExp`
  - [x] raise
    - [x] `raise e`, `raise`
    - [ ] `raise e from cause`
  - [x] classes
  - [x] other language features

- **runtime mechanisms**:
  - [x] `__abs__` (TODO: add `abs` builtin to call `__abs__`)
  - [x] `__enter__`
  - [x] `__exit__` (the third argument of `__exit__` is alway `None` in UnityPython!)

- **built-in functions and types** (only the necessary ones are included)
  - builtin types
    - [x] object
    - [x] int
    - [x] str (TODO: methods)
    - [x] float  (TODO: methods)
    - [x] bool  (TODO: methods)
    - [x] bytes (TODO: methods)
    - [x] bytearray (TODO: methods)
    - [x] slice  (TODO: methods)
    - [ ] (Unimportant) ~complex, memoryview~
    - [x] type
      **NOTE**: `type` is the only metaclass in UnityPython!
    - [x] `ref`: a UnityPython specific builtin, used for fast dictionary/attribute lookup
      ```python
       if dct.get(key, valueref := ref()):
          print(f"found {key}", valueref.value)
      ```
    - [x] `classmethod`
    - [x] `staticmethod`
    - [x] `property`: `property.setter`, `property.getter`
      **NOTE**: `fget`, `fset` are exposed yet; `property.deleter` is not implemented
  - [x] (not in the plan) ~NotImplemented~

  - builtin exception types (https://docs.python.org/3/library/exceptions.html):
    - [x] BaseException
    - [ ] SystemExit
    - [ ] ~KeyboardInterrupt~
    - [ ] ~GeneratorExit~
    - [x] Exception
      - [ ]  ArithmeticError: subclasses
        - [ ] ~FloatingPointError (for future)~
        - [ ] OverflowError
        - [ ] ZeroDivisionError
      - [x] AssertionError
      - [x] AttributeError
      - [ ] BufferError
      - [x] ImportError
        - [ ] ModuleNotFoundError
      - [x] LookupError
        - [x] IndexError
        - [x] KeyError
       - [x] NameError
           - [ ] UnboundLocalError
       - [x] RuntimeError
         - [x] NotImplementedError
         - [ ] RecursionError
         - [ ] SyntaxError
       - [ ] SystemError
       - [x] TypeError
       - [x] ValueError
       - [x] **NativeError** represents .NET exceptions
  - builtin functions/callables (https://docs.python.org/3/library/functions.html)
    - [x] `iter`
    - [x] `Task.Yield` (UnityPython specific): used for `yield` in `async` functions, the semantic is waiting for the next event loop.
    - [x] `print`
    - [x] `map`, `filter`
    - [x] `abs` (`__abs__` support?)
    - [x] `all`, `any`
    - [x] `bin`
    - [ ] ~`callable`~
    - [x] `chr`, `ord`, `oct`, `hex`
    - [x] `getattr`, `setattr`
    - [x] `enumerate`
    - [x] `hash`
    - [ ] ~id~ (impossible to implement, at least cannot be an int)
    - [x] `isinstance`, `issubclass`
    - [x] `range`
    - [x] `repr`: handle circular references (e.g., a list contained in the itself, deep or shallow)
    - [x] `reversed`
    - [x] `round`
    - [ ] ~`super`~
    - [x] `sorted`
    - [x] `sum`
    - [x] `pow`
    - [x] `zip`
    - [ ] ~`__import__`~
    - [ ] ~`globals`, `vars`, `locals`, `breakpoint`~

- runtime mechanisms
  - [x] inline cache

    object fields are stored in arrays rather than in dictionaries; writing and reading attributes are using inline cache (see `IC.*.cs`) for fast interpreter and low memory assumption
  - [x] error positions in exception stacktrace
    ```c#
    Stack<int> traceback = frame.traceback;
    callstack.Push(current);
    // interpreter
    callstack.Pop();
    ```
    - [x] traceback
    - [x] metadata compression
    - [ ] (Enhancement) fold successive tracebacks
  - [x] `__init_subclass__`

- tooling/IDE:
  - [x] builtins.py: Pylance-specific stub files for UnityPython

- Unity Modules

**Comment by thautwarm** [comment]
we keep only `__name__` and `__package__` is not used, this is because the module spec is not dynamically imported. No need to resolve.

**Comment by thautwarm** [comment]
Intentionally not support `__delattr__` because such feature is difficult to work with IDEs.

**Comment by thautwarm** [comment]
CPython `__getattr__` cannot be implemented efficiently as we want to use native c# exceptions as Python exceptions.
Modified `__getattr__` protocols can be efficient (`getattr(o, attr, ref) -> bool`), but this does not work with IDEs because the typing rules of `a.b` is hard-coded even in Pylance.

I'm going to drop magic methods like `__getattr__` and `__setattr__` to have fast `getattr` reflection.

**Comment by thautwarm** [comment]
we drop `__missing__`, the reason is similar to dropping `__getattr__`.

**Comment by thautwarm** [comment]
If one day any python static analyzer supports defining custom semantics for the syntax `a[b]` and `a.b`, we can support them easily.

At the current stage, it's doable to support them all, but this is a two-door design and causes unsolvable performance issues, which is the reason for not supporting them currently.

**Comment by thautwarm** [comment]
`__import__`  will not be implemented at the current stage.
We should provide a similar API to wrap `RTS.import_from_module`.

```c#
public static Stack<(TrStr, TrObject)> import_from_module(
       [AllowNull] string module,
       int level,
       Dictionary<TrObject, TrObject> globals,
       [AllowNull] string[] __all__
)

```

**Comment by thautwarm** [comment]
Focusing on tests: #26

**Comment by thautwarm** [comment]
The unsupported features will be documented.
